# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [74]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [75]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv(Path("Resources/applicants_data.csv"))

# Review the DataFrame
applicant_data_df.head()

        EIN                                      NAME  ... ASK_AMT IS_SUCCESSFUL
0  10520599              BLUE KNIGHTS MOTORCYCLE CLUB  ...    5000             1
1  10531628    AMERICAN CHESAPEAKE CLUB CHARITABLE TR  ...  108590             1
2  10547893        ST CLOUD PROFESSIONAL FIREFIGHTERS  ...    5000             0
3  10553066            SOUTHSIDE ATHLETIC ASSOCIATION  ...    6692             1
4  10556103  GENETIC RESEARCH INSTITUTE OF THE DESERT  ...  142590             1

[5 rows x 12 columns]

In [76]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [77]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(columns=["EIN","NAME"])

# Review the DataFrame
applicant_data_df.head()

  APPLICATION_TYPE       AFFILIATION  ... ASK_AMT IS_SUCCESSFUL
0              T10       Independent  ...    5000             1
1               T3       Independent  ...  108590             1
2               T5  CompanySponsored  ...    5000             0
3               T3  CompanySponsored  ...    6692             1
4               T3       Independent  ...  142590             1

[5 rows x 10 columns]

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [78]:
# Create a list of categorical variables 
categorical_variables = list(applicant_data_df.dtypes[applicant_data_df.dtypes == "object"].index)

# Display the categorical variables list
categorical_variables

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [79]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [80]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

In [81]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(encoded_data, columns = enc.get_feature_names(categorical_variables))

# Review the DataFrame
encoded_df.head()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

   APPLICATION_TYPE_T10  ...  SPECIAL_CONSIDERATIONS_Y
0                   1.0  ...                       0.0
1                   0.0  ...                       0.0
2                   0.0  ...                       0.0
3                   0.0  ...                       0.0
4                   0.0  ...                       0.0

[5 rows x 114 columns]

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [82]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
numerical_variables = applicant_data_df.drop(columns=categorical_variables)
encoded_df = pd.concat([encoded_df, numerical_variables], axis=1)

# Review the Dataframe
encoded_df.head()

   APPLICATION_TYPE_T10  APPLICATION_TYPE_T12  ...  ASK_AMT  IS_SUCCESSFUL
0                   1.0                   0.0  ...     5000              1
1                   0.0                   0.0  ...   108590              1
2                   0.0                   0.0  ...     5000              0
3                   0.0                   0.0  ...     6692              1
4                   0.0                   0.0  ...   142590              1

[5 rows x 117 columns]

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [83]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df["IS_SUCCESSFUL"]

# Display a sample of y
y.head()

0    1
1    1
2    0
3    1
4    1
Name: IS_SUCCESSFUL, dtype: int64

In [84]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop(columns="IS_SUCCESSFUL")

# Review the features DataFrame
X.head()

   APPLICATION_TYPE_T10  APPLICATION_TYPE_T12  ...  STATUS  ASK_AMT
0                   1.0                   0.0  ...       1     5000
1                   0.0                   0.0  ...       1   108590
2                   0.0                   0.0  ...       1     5000
3                   0.0                   0.0  ...       1     6692
4                   0.0                   0.0  ...       1   142590

[5 rows x 116 columns]

### Step 6: Split the features and target sets into training and testing datasets.

In [85]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [86]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset.
# ^ I think this should read "Scaler or Tranform the Train and Test" datasets.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [87]:
# Define the the number of inputs (features) to the model
number_input_features = len(X.iloc[0])

# Review the number of features
number_input_features

116

In [88]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [89]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 = (len(X.iloc[0] + 1) // 2)

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

58

In [90]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  (hidden_nodes_layer1 +1) // 2

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

29

In [91]:
# Create the Sequential model instance
nn = Sequential()

In [92]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation = "relu"))

In [93]:
# Add the second hidden layer
nn.add(Dense(units = hidden_nodes_layer2, activation="relu"))

In [94]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=1, activation="sigmoid"))

In [95]:
# Display the Sequential model summary
nn.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_10 (Dense)            (None, 58)                6786

 dense_11 (Dense)            (None, 29)                1711

 dense_12 (Dense)            (None, 1)                 30

=================================================================
Total params: 8,527
Trainable params: 8,527
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [96]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [97]:
# Fit the model using 50 epochs and the training data
model = nn.fit(X_train_scaled, y_train, epochs=50, verbose=0)

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [98]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5576 - accuracy: 0.7273 - 388ms/epoch - 1ms/step
Loss: 0.5575578808784485, Accuracy: 0.7273469567298889

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [99]:
# Set the model's file path
file_path = Path("Resources/AlphabetSoup.h5")

# Export your model to a HDF5 file
nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [100]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [101]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [102]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = (len(X_train.iloc[0] + 1) // 2)

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

58

In [103]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2_A1 =  (hidden_nodes_layer1_A1 +1) // 2

# Review the number hidden nodes in the second layer
hidden_nodes_layer2_A1

29

In [104]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [105]:
# First hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer1_A1, input_dim=number_input_features, activation = "relu"))

# Add second hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer2_A1, activation = "relu"))


# Output layer
nn_A1.add(Dense(units=1, activation="sigmoid"))


# Check the structure of the model
nn_A1.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_13 (Dense)            (None, 58)                6786

 dense_14 (Dense)            (None, 29)                1711

 dense_15 (Dense)            (None, 1)                 30

=================================================================
Total params: 8,527
Trainable params: 8,527
Non-trainable params: 0
_________________________________________________________________

In [106]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [107]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5759 - accuracy: 0.7206
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5549 - accuracy: 0.7295
Epoch 3/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5511 - accuracy: 0.7301
Epoch 4/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5480 - accuracy: 0.7317
Epoch 5/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7321
Epoch 6/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7333
Epoch 7/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7344
Epoch 8/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7337
Epoch 9/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7346
Epoch 10/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7349
Epoch 11/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7354
Epoch 12/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7352
Epoch 13/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7347
Epoch 14/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7361
Epoch 15/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7356
Epoch 16/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7362
Epoch 17/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7367
Epoch 18/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5386 - accuracy: 0.7374
Epoch 19/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5380 - accuracy: 0.7373
Epoch 20/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7366
Epoch 21/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5380 - accuracy: 0.7382
Epoch 22/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5372 - accuracy: 0.7376
Epoch 23/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7392
Epoch 24/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7380
Epoch 25/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5367 - accuracy: 0.7394
Epoch 26/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7388
Epoch 27/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5357 - accuracy: 0.7393
Epoch 28/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5357 - accuracy: 0.7382
Epoch 29/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7395
Epoch 30/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7395
Epoch 31/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7386
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7376
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7397
Epoch 34/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7401
Epoch 35/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7383
Epoch 36/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7400
Epoch 37/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5334 - accuracy: 0.7407
Epoch 38/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7409
Epoch 39/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5330 - accuracy: 0.7398
Epoch 40/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7404
Epoch 41/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5331 - accuracy: 0.7406
Epoch 42/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7390
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7413
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7404
Epoch 45/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5320 - accuracy: 0.7404
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5323 - accuracy: 0.7404
Epoch 47/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5320 - accuracy: 0.7409
Epoch 48/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5321 - accuracy: 0.7412
Epoch 49/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7406
Epoch 50/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5317 - accuracy: 0.7409

#### Alternative Model 2

In [108]:
# Define the the number of inputs (features) to the model
number_input_features_A2 = len(X_train.iloc[0])

# Review the number of features
number_input_features_A2

116

In [109]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [110]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = 58

# Review the number of hidden nodes in the first layer
display(hidden_nodes_layer1_A2)

# Define nodes for second hidden layer
hidden_nodes_layer2_A2 = 29

# Preview hidden layer 2.
display(hidden_nodes_layer2_A2)

# Define number of nodes for third hidden layer
hidden_nodes_layer3_A2 = (hidden_nodes_layer2_A2 + 1) // 2

display(hidden_nodes_layer3_A2)

58

29

15

In [111]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [112]:
# First hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer1_A2, input_dim=number_input_features_A2, activation = "relu"))
# Second hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer2_A2, activation = "relu"))
#Third hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer3_A2, activation = "relu"))
# Output layer
nn_A2.add(Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_A2.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_16 (Dense)            (None, 58)                6786

 dense_17 (Dense)            (None, 29)                1711

 dense_18 (Dense)            (None, 15)                450

 dense_19 (Dense)            (None, 1)                 16

=================================================================
Total params: 8,963
Trainable params: 8,963
Non-trainable params: 0
_________________________________________________________________

In [113]:
# Compile the model
nn_A2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [114]:
# Fit the model
model_A2 = nn_A2.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5730 - accuracy: 0.7201
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5517 - accuracy: 0.7294
Epoch 3/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5479 - accuracy: 0.7306
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7321
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5451 - accuracy: 0.7324
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5430 - accuracy: 0.7338
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7354
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7355
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7343
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7362
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7355
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7375
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7360
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7379
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7379
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7374
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7391
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7399
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7383
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5361 - accuracy: 0.7384
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7383
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7390
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7383
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7393
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7395
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7400
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5345 - accuracy: 0.7398
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5345 - accuracy: 0.7400
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5341 - accuracy: 0.7396
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7397
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5341 - accuracy: 0.7397
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7400
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5337 - accuracy: 0.7405
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5334 - accuracy: 0.7404
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5329 - accuracy: 0.7415
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5328 - accuracy: 0.7398
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5325 - accuracy: 0.7406
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5320 - accuracy: 0.7404
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5320 - accuracy: 0.7405
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5324 - accuracy: 0.7408
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5325 - accuracy: 0.7415
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5320 - accuracy: 0.7409
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5318 - accuracy: 0.7418
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5315 - accuracy: 0.7409
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5316 - accuracy: 0.7412
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5314 - accuracy: 0.7411
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5312 - accuracy: 0.7417
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5313 - accuracy: 0.7408
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5308 - accuracy: 0.7418
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5301 - accuracy: 0.7420

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [115]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 0s - loss: 0.5576 - accuracy: 0.7273 - 296ms/epoch - 1ms/step
Loss: 0.5575578808784485, Accuracy: 0.7273469567298889

In [116]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 0s - loss: 0.5595 - accuracy: 0.7320 - 392ms/epoch - 1ms/step
Loss: 0.5595001578330994, Accuracy: 0.7320116758346558

In [117]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 0s - loss: 0.5567 - accuracy: 0.7298 - 407ms/epoch - 2ms/step
Loss: 0.5566878914833069, Accuracy: 0.7297959327697754

### Step 3: Save each of your alternative models as an HDF5 file.

In [118]:
# Set the file path for the first alternative model
file_path = Path("Resources/AlphabetSoup_A1.h5")

# Export your model to a HDF5 file
nn_A1.save(file_path)

In [119]:
# Set the file path for the second alternative model
file_path = Path("Resources/AlphabetSoup_A2.h5")

# Export your model to a HDF5 file
nn_A2.save(file_path)